export const DEFAULT_VENUE_CHECKLIST: readonly string[] = [
  "Estacionamento (quantas vagas?)",
  "Acessibilidade para PCD",
  "Banheiros suficientes para a quantidade prevista",
  "Gerador ou no-break em caso de queda de energia",
  "Cobertura/plano B para chuva",
  "Climatização (ar condicionado / ventilação)",
  "Suíte ou espaço para a noiva se preparar",
  "Cozinha estruturada para o buffet",
  "Horário máximo de término obrigatório?",
  "Restrição de som / decibéis após X horas?",
  "Área externa / fumódromo",
  "Permite fogos / sparklers / fumaça?",
  "Permite buffet externo?",
  "Permite bolo / doces externos?",
  "Taxa de rolha para bebidas externas?",
  "Hospedagem nos arredores para convidados",
  "Política de cancelamento (até quantos dias?)",
  "Caução exigida?",
  "Seguro de evento incluso?",
  "Mobiliário incluso (mesas, cadeiras, louça)?",
];
