# Habilite financiamento opcional do projeto.
# Descomente / preencha apenas se você quiser receber doações.
#
# Documentação: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: guiloklex-hub
# ko_fi: guiloklex-hub
# buy_me_a_coffee: guiloklex-hub
# custom: ["11970985308", "https://www.paypal.com/donate?hosted_button_id=11970985308"]
