# Habilite financiamento opcional do projeto.
# Descomente / preencha apenas se você quiser receber doações.
#
# Documentação: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: guiloklex-hub
ko_fi: guiloklexhub
custom: ["https://www.paypal.com/donate/?business=8FXKSMKURNKW8&no_recurring=0&currency_code=BRL"]
